### ISSUE TITLE
phantomjs 已经废弃需要升级

### ISSUE THREAD

**Issue by loskael** [caihuiji/node-highcharts-exporting#5]
参考 https://github.com/BetterJS/badjs-web/issues/23

### 启动时报错：
```
/Users/kael/Github/betterjs/badjs-web/node_modules/node-highcharts-exporting/index.js:20
        throw err;
        ^
Error: Command failed: /Users/kael/Github/betterjs/badjs-web/node_modules/phantomjs/lib/phantom/bin/phantomjs /Users/kael/Github/betterjs/badjs-web/node_modules/node-highcharts-exporting/lib/highcharts-convert.js -host 127.0.0.1 -port 8787

    at ChildProcess.exithandler (child_process.js:206:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:498:12)
```
### 环境说明：
node -v
v6.9.1

uname -a
Darwin bogon 16.4.0 Darwin Kernel Version 16.4.0: Thu Dec 22 22:53:21 PST 2016; root:xnu-3789.41.3~3/RELEASE_X86_64 x86_64

**Comment by caihuiji** [comment]
fix

**Comment by loskael** [comment]
按官方的建议，应该是升级为 [phantomjs-prebuilt](https://www.npmjs.com/package/phantomjs-prebuilt)

> DEPRECATED
> Pre-2.0, this package was published to NPM as phantomjs. We changed the name to phantomjs-prebuilt at the request of PhantomJS team.
> Please update your package references from phantomjs to phantomjs-prebuilt

**Comment by gebilaoman** [comment]
> fix

怎么fix的
